### ISSUE TITLE
'ValueError: No Points Given' when running projectUV

### ISSUE THREAD

**Issue by sethnavon** [PennyHow/PyTrx#29]
In my [forked repo](https://github.com/sethnavon/PyTrx/blob/master/Seth_Examples/orthorectification.py), in line 53 running projectUV returns a ValueError: No Points Given. Tracing this to the setProjection function in PyTrx/CamEnv.py, lines 852-862, before the projection, X, Y, and Z are all arrays with points, after the projection they are empty arrays. Thank you for any help you can offer.

**Comment by PennyHow** [comment]
@sethnavon I just checked, and using the CamEnv.showGCPs() you can see that one of your GCPs plots outside of your DEM extent (see plot below). Therefore, the camera model cannot project the GCP position from the DEM to the image plane as it is technically outside of the extent that has been modelled. 

In addition, I checked your internal camera parameters by calling some simple plotting functions offered with PyTrx. It appears that your distortion model is wrong, and the position of your principal point does not look right. The distortion model looks asymmetrical, which isn't unheard of, but highly unlikely for the camera model you were using. Also, the principal point should generally be around the physical centre of the image, whilst yours is offset by quite a lot.

Please check the positions of your GCPs and that they are in the same coordinate system as your DEM. If this is all correct then you need to change your DEM to match the same area that is shown in your images. Please also check your camera model (distortion parameters, focal length, principal point position) as it appears to be incorrect.

I will push my version of your orthorectification.py so you can recreate these plots to check your parameters

![for_seth](https://user-images.githubusercontent.com/28731816/121532787-718e3580-c9de-11eb-9388-a02d0bc17b14.jpg)
.
