### ISSUE TITLE
CameraEnvironmentData_KR2_2014.txt Calibration Question

### ISSUE THREAD

**Issue by shahinmg** [PennyHow/PyTrx#47]
Hi Penny, what do the 6 and 9 refer to in line 24 of CameraEnvironmentData_KR2_2014.txt when setting the calibration image path?

[../Examples/camenv_data/calib/KR2_calibimgs/*.JPG, 6, 9]

**Comment by shahinmg** [comment]
row and columns of the checkerboard! I just had to dig deeper in the code

**Comment by PennyHow** [comment]
Ah yes, I was trying to dig this out from our documentation to answer you with something to refer to. Glad you found it first!
